package org.zzn.hospital.enums;

public enum Speciality {
    GENERAL_PRACTITIONER,
    CARDIOLOGIST,
    DERMATOLOGIST,
    PEDIATRICIAN,
    NEUROLOGIST,
    PSYCHIATRIST,
    ONCOLOGIST,
    GYNECOLOGIST,
    RADIOLOGIST,
    ORTHOPEDIC_SURGEON,
    ENT_SPECIALIST,
    UROLOGIST,
    OPHTHALMOLOGIST,
    ANESTHESIOLOGIST,
    ENDOCRINOLOGIST
}
